carshop_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('order.urls')),
    path('search/', include('search_app.urls')),
    path('', include('shop.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views
app_name='cart'
urlpatterns = [
path('add/<uuid:product_id>/', views.add_cart, name='add_cart'),
path('', views.cart_detail, name='cart_detail'),
path('remove/<uuid:product_id>/', views.cart_remove, name='cart_remove'),
path('full_remove/<uuid:product_id>/', views.full_remove, name='full_remove'),
]

shop/urls.py
from django.urls import path
from . import views
from .views import (
    CarCreateView,
    CarDetailView,
    CarListView, 
    CarDeleteView,
    add_comment,
    )

app_name = 'shop'

urlpatterns = [
    path('', views.prod_list,name = 'all_products'),
    path('<uuid:category_id>/', views.prod_list, name = 'products_by_category'),
    path('<uuid:category_id>/<uuid:product_id>/', views.product_detail, name = 'product_detail'),
    path('newcomment/<int:pk>/', add_comment, name='add_comment'),
    path('new/', CarCreateView.as_view(), name='car_create'),
    path('<int:pk>/delete/',CarDeleteView.as_view(), name = 'car_delete'),
    path('<int:pk>/', CarDetailView.as_view(), name='car_detail'),
]

shop/models.py
from django.db import models
import uuid
from django.urls import reverse
from django.contrib.auth import get_user_model

class Category(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False)
    name = models.CharField(max_length=250, unique=True)
    description = models.TextField(blank = True)
    image = models.ImageField(upload_to = 'category', blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse('shop:products_by_category', args=[self.id])

    def __str__(self):
        return self.name

class Product(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False)
    name = models.CharField(max_length=250, unique=True)
    description = models.TextField(blank = True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to = 'product', blank=True)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, blank = True, null= True)
    updated = models.DateTimeField(auto_now=True, blank = True, null= True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.category.id, self.id])

    def __str__(self):
        return self.name

class Comment(models.Model):
    car = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='comments')
    comment = models.TextField(max_length= 400)
    author =  models.ForeignKey(get_user_model(), on_delete=models.CASCADE,)

    def __str__(self):
        return self.comment
    
    def get_absolute_url(self):
        return reverse('car_list')

shop/forms.py
from . models import Comment
from django import forms

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment 
        fields = ["comment"]

shop/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Category, Product, Comment
from django.core.paginator import Paginator, EmptyPage, InvalidPage
from django.views.generic.edit import CreateView, DeleteView
from django.views.generic import DetailView, ListView
from django.urls import reverse_lazy
from .forms import CommentForm


def prod_list(request, category_id=None):
    category = None
    products = Product.objects.filter(available=True)
    if category_id:
        category = get_object_or_404(Category, id=category_id)
        products = Product.objects.filter(category=category, available=True)

    paginator = Paginator(products, 6)
    try:
        page = int(request.GET.get('page', '1'))
    except:
        page = 1
    try:
        products = paginator.page(page)
    except (EmptyPage,InvalidPage):
        products = paginator.page(paginator.num_pages)

        
    return render(request, 'shop/category.html',{'category':category, 'prods':products})


def product_detail(request, category_id, product_id):
    product = get_object_or_404(Product, category_id=category_id, id=product_id)
    return render(request, 'shop/product.html', {'product': product})


class CarCreateView(CreateView):
    model = Product
    template_name = 'temp_car/car_create.html'
    fields = ['name', 'description', 'category', 'price', 'image', 'stock', 'available']



class CarDetailView(DetailView):
    model = Product
    template_name = 'temp_car/car_detail.html'

class CarListView(ListView):
    model = Product
    context_object_name = "car_list"
    template_name = 'temp_car/car_list.html'

class CarDeleteView(DeleteView):
    model = Product
    template_name = 'temp_car/car_delete.html'
    success_url = reverse_lazy('car_list')
    
def add_comment(request, pk):
    car = get_object_or_404(Product, pk=pk)
    form = CommentForm(request.POST)
    if form.is_valid():
        author = request.user
        comment = form.cleaned_data['comment']
        commentObject = Comment(car = car, comment=comment, author = author)
        commentObject.save()

        return redirect('car_detail', car.pk)

    form = CommentForm()
    context = {
        "car":car,
        "form":form
    }
    return render(request, 'temp_comments/comment_create.html', context)

shop/templates/shop/category.html
{% extends "base.html" %}
{% load static %}
{% block metadescription %}
{% if category %}
{{ category.description|truncatewords:155 }}
{% else %}
{% endif %}
{% endblock %}
{% block title %}
{% if category %}
{{ category.name }} - Carz4Sale
{% else %}
{% endif %}
{% endblock %}
{% block content %}
<!--Breadcrumb navigation-->
<!-- {% if category %}
<div>
    <div>
        <p><a href="{% url 'shop:all_products' %}">Our Products</a> | {{category.name}}</p>
    </div>
</div>
{% endif %}
<div>
    {% if category %}
    <img src="{{category.image.url}}" alt="{{category.name}}">
</div>
<br>
<div>
    <h1>{{category.name}}</h1>
    <p>{{category.description}}</p>
</div>
</div>
<br>
{% endif %} -->
<div class="text_margin">
    <h1 class="homepage_title">Our Products</h1>
    <p class="homepage_title">Finding the best car for with the best deal has never been easier than on Carz4Sale!</p>
    {% if user.is_superuser %}
    <hr>
    <h3>Staff Options</h3>
    <button class="btn"><a class="btn_text" href="{% url 'shop:car_create' %}">+add car</a></button>
    <hr>
    {% endif %}
    <br>
    <div class="container">
        <div class="row mx-auto">
            {% for product in prods %}
            <div class="col-md-4 my_bottom_margin">
                <div class="card" style="min-width:18rem;">
                    <a class="img" href="{{product.get_absolute_url}}"><img class="card-img-top
     my_image" src="{{ product.image.url }}" alt="{{product.name}}"></a>
                    <div class="card-body">

                        <h4><a class="link_decoration" href="{{product.get_absolute_url}}">{{product.name}}</a></h4>
                        <p>€{{product.price}}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="mx-auto">
            {% if prods.paginator.num_pages > 1 %}
            <br>
            <div class="homepage_title">
                {% for pg in prods.paginator.page_range %}
                <button class="btn"><a href="?page={{pg}}" class="btn_text {%
        if products.number == pg %}active{% endif
        %}">{{pg}}</a></button>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        <br>
    </div>
</div>
{% endblock %}

shop/templates/shop/product.html
{% extends "base.html" %}
{% load static %}
{% block metadescription %}
{{ product.description|truncatewords:155 }}
{% endblock %}
{% block title %}
{{ product.name }} - Carz4Sale
{% endblock %}
{% block content %}
<div class="navbar_text">
    <div>
        <button class="btn"><a class="btn_text" href="{% url 'shop:all_products' %}">Return Home</a></button>
    </div>
    <div class="">
        <br>
        <div class="prod_container">
            <div>
                <div>
                    <img class="prod_img" src="{{product.image.url}}" alt="{{product.name}}">
                </div>
            </div>
            <div class="">
                <div class="prod_text">
                    <h1>{{product.name}}</h1>
                    <p>€{{product.price}}</p>
                    <p>Product Description:</p>
                    <p>{{product.description}}</p>
                    {% if product.stock == 0%}
                    <p><b>Out of Stock</b></p>
                    {% else %}
                    <button class="btn"><a class="btn_text" href="{% url 'cart:add_cart' product.id %}">Add to Cart</a></button>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}